version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Zipping repository files..."
      - zip -r Code-Deploy-package.zip .
  post_build:
    commands:
      - echo "Uploading zip to S3..."
      - aws s3 cp Code-Deploy-package.zip s3://app-packaged-bucket/demo-deploy-code/Code-Deploy-package.zip
